# -*- coding: utf-8 -*-
"""data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18bisnkYiTmRZEW1wxY1miMsi-LPWEd0s
"""
import argparse
import pickle
import pandas as pd
from sklearn.preprocessing import normalize
from sklearn.neighbors import NearestNeighbors
from sklearn.utils import check_random_state
import numpy as np
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt


def prepare(X, y, ids, random_state=42):
    """Prepare data: L2-normalize features for cosine geometry"""
    rs = check_random_state(random_state)
    # L2-normalize for cosine geometry
    Xn = normalize(X, norm='l2')
    y = np.asarray(y)
    ids = np.asarray(ids)
    return Xn, y, ids, rs

def stratified_sample(y, ids, Xn, per_class=100, rs=None):
    """Randomly sample per_class samples from each class"""
    out = {}
    for cls in ["normal", "suspecte"]:
        idx = np.where(y == cls)[0]
        pick = rs.choice(idx, size=min(len(idx), len(idx)), replace=False)
        out[cls] = pick
    return out["normal"], out["suspecte"]

def class_centroids(Xn, y):
    """Compute normalized centroids for each class"""
    cent = {}
    for cls in ["normal", "suspecte"]:
        cent[cls] = normalize(Xn[y==cls].mean(axis=0).reshape(1,-1))[0]
    return cent

def centroid_flip_score(Xn, y, cent):
    """
    Compute centroid flip score: how much closer to the other class centroid
    Higher score = more suspicious (closer to the wrong centroid)
    """
    # cosine similarity to each centroid
    Cn = Xn @ cent["normal"]
    Cs = Xn @ cent["suspecte"]
    own = np.where(y=="normal", Cn, Cs)
    other = np.where(y=="normal", Cs, Cn)
    # suspicious if similarity(other) - similarity(own) is large
    return other - own, Cn, Cs

def knn_disagreement(Xn, y, k=30):
    """
    Compute k-NN label disagreement: fraction of neighbors with opposite label
    Also returns distance to nearest opposite-class neighbor
    """
    nn = NearestNeighbors(n_neighbors=min(k+1, len(Xn)), metric="cosine")
    nn.fit(Xn)
    dists, nbrs = nn.kneighbors(Xn, return_distance=True)
    nbrs = nbrs[:,1:]   # drop self
    dists = dists[:,1:]
    ynbr = y[nbrs]
    # fraction of neighbors with the other label
    other = np.where(y=="normal", "suspecte", "normal")
    disagree = (ynbr == other[:,None]).mean(axis=1)
    # nearest distance to any point of the other class (for context)
    mask_other = (ynbr == other[:,None])
    nearest_other_dist = np.where(mask_other, dists, np.inf).min(axis=1)
    return disagree, nearest_other_dist

def z_score(x):
    """Compute z-scores for normalization"""
    m, s = np.nanmean(x), np.nanstd(x) + 1e-12
    return (x - m) / s

print("Label quality analysis functions loaded successfully!")

def rank_for_review(Xn, y, ids, idx_subset, cent, k=30):
    """
    Rank a subset of samples by mislabel likelihood

    Returns a DataFrame with:
    - id: sample identifier
    - label: assigned label
    - flip_score: centroid flip score
    - knn_disagree: k-NN disagreement rate
    - cos_sim_to_normal: cosine similarity to normal centroid
    - cos_sim_to_suspecte: cosine similarity to suspecte centroid
    - nearest_other_dist: distance to nearest opposite-class sample
    - combined_score: z(flip_score) + z(knn_disagree) - higher = more suspicious
    """
    flip, Cn, Cs = centroid_flip_score(Xn, y, cent)
    disagree, nearest_other_dist = knn_disagreement(Xn, y, k=k)

    sub = idx_subset
    df = pd.DataFrame({
        "id": ids[sub],
        "label": y[sub],
        "flip_score": flip[sub],
        "knn_disagree": disagree[sub],
        "cos_sim_to_normal": Cn[sub],
        "cos_sim_to_suspecte": Cs[sub],
        "nearest_other_dist": nearest_other_dist[sub],
    })
    df["combined_score"] = z_score(df["flip_score"]) + z_score(df["knn_disagree"])
    df = df.sort_values("combined_score", ascending=False).reset_index(drop=True)
    return df

def produce_review_tables(X, y, ids, per_class=100, k=30, random_state=42, save_prefix="", Th=1):
    """
    Main function to produce review tables

    Args:
        X: feature matrix (N, D)
        y: labels (N,)
        ids: sample identifiers (N,)
        per_class: number of samples to randomly select from each class
        k: number of neighbors for k-NN disagreement
        random_state: random seed for reproducibility
        save_prefix: prefix for output CSV files

    Returns:
        df_norm, df_susp: DataFrames with ranked samples for each class
    """
    print(f"Preparing data with {len(X)} samples...")
    Xn, y, ids, rs = prepare(X, y, ids, random_state)

    print(f"Sampling {per_class} samples from each class...")
    idx_norm, idx_susp = stratified_sample(y, ids, Xn, per_class, rs)

    print("Computing class centroids...")
    cent = class_centroids(Xn, y)

    print(f"Ranking samples by mislabel likelihood (k={k})...")
    df_norm = rank_for_review(Xn, y, ids, idx_norm, cent, k=k)
    df_susp = rank_for_review(Xn, y, ids, idx_susp, cent, k=k)

    filtered_df_norm = df_norm[df_norm["combined_score"] < Th].reset_index(drop=True)
    filtered_df_susp = df_susp[df_susp["combined_score"] < Th].reset_index(drop=True)

    # Save both the random samples and the ranked views
    print(f"Saving results with prefix '{save_prefix}'...")
    pd.DataFrame({"id": ids[idx_norm], "label": y[idx_norm]}).to_csv(
        f"{save_prefix}sample_no_th_{Th}.csv", index=False
    )
    pd.DataFrame({"id": ids[idx_susp], "label": y[idx_susp]}).to_csv(
        f"{save_prefix}sample_sus_th_{Th}.csv", index=False
    )

    filtered_df_norm.to_csv(f"{save_prefix}generate_sante_txt_files/review_candidates_no_th_{Th}.csv", index=False)
    filtered_df_susp.to_csv(f"{save_prefix}generate_sante_txt_files/review_candidates_sus_th_{Th}.csv", index=False)

    print("\n✓ Analysis complete! Files saved:")
    print(f"  - {save_prefix}sample_no_v2.csv")
    print(f"  - {save_prefix}sample_sus_v2.csv")
    print(f"  - {save_prefix}review_candidates_no_v2.csv")
    print(f"  - {save_prefix}review_candidates_sus_v2.csv")

    return filtered_df_norm, filtered_df_susp


def main():
    # Load features
    args = parser.parse_args()
    normal_features = args.no_pkl_files
    sus_features = args.sus_pkl_files

    with open(str(normal_features), 'rb') as f:
        features_dict_normal = pickle.load(f)

    with open(str(sus_features), 'rb') as f:
        features_dict_suspecte = pickle.load(f)

    features_dict = {**features_dict_normal, **features_dict_suspecte}

    all_files = list(features_dict.keys())
    all_classes = [file[-12:-4] for file in all_files]

    classes = list(set(all_classes))
    print(classes)

    # Prepare data for t-SNE
    features_list = []
    labels_list = []

    classes = ['normal', 'suspecte']

    for filename, features in features_dict.items():
        # Extract class from filename (last 8 characters before extension)
        class_label = filename[-12:-4]
        class_label = 'suspecte' if class_label[0] == 'z' else 'normal'
        features_list.append(features)
        labels_list.append(class_label)

    # Convert to numpy array
    X = np.array(features_list)
    y = np.array(labels_list)

    print(f"Features shape: {X.shape}")
    print(f"Number of samples: {len(y)}")
    print(f"Classes: {classes}")

    # Apply t-SNE
    print("Applying t-SNE...")
    tsne = TSNE(n_components=2, random_state=42, perplexity=30, max_iter=1000)
    X_tsne = tsne.fit_transform(X)

    # Create the plot
    plt.figure(figsize=(12, 8))

    # Plot each class with a different color
    colors = plt.cm.bwr(np.linspace(0, 1, len(classes)))
    for idx, class_name in enumerate(classes):
        mask = y == class_name
        plt.scatter(X_tsne[mask, 0], X_tsne[mask, 1],
                    c=[colors[idx]], label=class_name,
                    alpha=0.6, s=50, edgecolors='black', linewidth=0.5)

    plt.xlabel('t-SNE Component 1', fontsize=12)
    plt.ylabel('t-SNE Component 2', fontsize=12)
    plt.title('t-SNE Visualization of Features by Class', fontsize=14, fontweight='bold')
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=10)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig("generate_sante_txt_files/SNE Components")
    plt.close()

    print(f"t-SNE visualization complete!")

    from sklearn.decomposition import PCA

    # Apply PCA
    print("Applying PCA...")
    pca = PCA(n_components=2, random_state=42)
    X_pca = pca.fit_transform(X)

    print(f"Explained variance ratio: {pca.explained_variance_ratio_}")
    print(f"Total variance explained: {sum(pca.explained_variance_ratio_):.4f}")

    # Create the plot
    plt.figure(figsize=(12, 8))

    # Plot each class with a different color
    colors = plt.cm.bwr(np.linspace(0, 1, len(classes)))
    X_pca[:,0] = np.clip(X_pca[:,0], 0, 0.1)
    for idx, class_name in enumerate(classes):
        mask = y == class_name
        plt.scatter(X_pca[mask, 0], X_pca[mask, 1],
                    c=[colors[idx]], label=class_name,
                    alpha=0.6, s=50, edgecolors='black', linewidth=0.5)

    plt.xlabel(f'PC1 ({pca.explained_variance_ratio_[0]:.2%} variance)', fontsize=12)
    plt.ylabel(f'PC2 ({pca.explained_variance_ratio_[1]:.2%} variance)', fontsize=12)
    plt.title('PCA Visualization of Features by Class', fontsize=14, fontweight='bold')
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=10)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig("generate_sante_txt_files/PCA")
    plt.close()

    print(f"PCA visualization complete!")

    """## Label Quality Analysis
    
    This section implements a robust system to identify potentially mislabeled samples using:
    1. **Centroid flip score**: measures how close a sample is to the opposite class centroid
    2. **k-NN label disagreement**: measures how many neighbors have a different label
    
    The output will be CSV files ranking samples by mislabel likelihood.
    
    """
    print("Main analysis function loaded successfully!")

    # Prepare IDs from the features_dict keys
    ids = np.array(list(features_dict.keys()))

    # Run the analysis
    df_norm, df_susp = produce_review_tables(
        X=X,
        y=y,
        ids=ids,
        per_class=100,  # Sample 100 from each class
        k=30,  # Use 30 nearest neighbors
        random_state=42,
        save_prefix="",  # No prefix, saves directly to current directory
        Th = int(args.Th)
    )

    print("\n" + "=" * 60)
    print("Analysis Summary")
    print("=" * 60)
    print(f"\nTotal samples analyzed: {len(X)}")
    print(f"  - Normal: {(y == 'normal').sum()}")
    print(f"  - Suspecte: {(y == 'suspecte').sum()}")
    print(f"\nSamples per class for review: 100")
    print(f"k-NN neighbors used: 30")

    # Display top 20 most suspicious samples from each class

    print("=" * 80)
    print("TOP 20 MOST SUSPICIOUS 'NORMAL' SAMPLES")
    print("=" * 80)
    print("\nThese samples are labeled 'normal' but have characteristics of 'suspecte':\n")
    print(df_norm.head(20).to_string(index=True))

    print("\n\n" + "=" * 80)
    print("TOP 20 MOST SUSPICIOUS 'SUSPECTE' SAMPLES")
    print("=" * 80)
    print("\nThese samples are labeled 'suspecte' but have characteristics of 'normal':\n")
    print(df_susp.head(20).to_string(index=True))



if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        prog='partition data into 4 risk classes')
    parser.add_argument('--sus_pkl_files', type=str, help='path to the pkl files containing suspicious features')
    parser.add_argument('--no_pkl_files', type=str, help='path to the pkl files containing normal features')
    parser.add_argument('--Th', type=int, help='filtering threshold', default=1)

    main()


