"""
PARTITIONARE DATE IN 4 DIRECTOARE DE INTERES IN FUNCTIE DE CASELE DE RISC
!!!!!!!!!CLASA PLACARD NU ESTE LUATA IN COSIDERARE!!!!!!!!!!!
"""

import pandas as pd
import os
import shutil
import argparse


def main():

    args = parser.parse_args()
    root_dir = args.root_dir
    df = pd.read_csv(args.csv)

    df_matrix = df.loc[:, ["id_patient", "id_slide_crop", "cell_name", "id_path"]]
    no_options = ["no-sq-sup", "no-sq-int", "no-sq-baz", "no-gl-enc"]
    mz_options = ["mz-sq-sup", "mz-sq-int", "mz-sq-baz", "mz-gl-enc"]
    dz_options = ["dz-sq-sup", "dz-sq-int", "dz-sq-baz", "dz-gl-enc"]

    no_cells = df_matrix.loc[df_matrix['cell_name'].isin(no_options)].sample(frac=1).reset_index(drop=True)
    dz_cells = df_matrix.loc[df_matrix['cell_name'].isin(dz_options)].sample(frac=1).reset_index(drop=True)
    mz_cells = df_matrix.loc[df_matrix['cell_name'].isin(mz_options)].sample(frac=1).reset_index(drop=True)
    artefacts = df_matrix.loc[df_matrix['cell_name'].isin(["artefact"])].sample(frac=1).reset_index(drop=True)

    os.makedirs(os.path.join(root_dir, "normal"), exist_ok=True)
    os.makedirs(os.path.join(root_dir, "metaplazii"), exist_ok=True)
    os.makedirs(os.path.join(root_dir, "suspecte"), exist_ok=True)
    os.makedirs(os.path.join(root_dir, "artefacte"), exist_ok=True)

    for i, att, cells in [[range(len(no_cells)), "normal", no_cells], [range(len(mz_cells)), "metaplazii", mz_cells],
                   [range(len(dz_cells)), "suspecte", dz_cells], [range(len(artefacts)), "artefacte", artefacts]]:
        for idx in i:
            no_cell = cells.iloc[idx]
            cell_dir = no_cell['id_path']
            if "placard" in cell_dir:
                continue
            old_name = shutil.copy2(cell_dir, os.path.join(root_dir, att))
            new_name = os.path.join(os.path.dirname(os.path.dirname(cell_dir)), att,
                                     os.path.basename(os.path.dirname(cell_dir)) + "_" + os.path.basename(cell_dir))
            os.rename(old_name, new_name)
    print("Done with partitioning data")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog='partition data into 4 risk classes')
    parser.add_argument('--root_dir', type=str, help='path for the crops generated by generate_out_crops')
    parser.add_argument('--csv', type=str, help='path for the partition_info.csv')

    main()