# EfficientNet-B0 Classification Configuration
# Example configuration for image classification with EfficientNet-B0

experiment:
  name: efficientnet_classification
  seed: 42

data:
  dataset_type: classification
  data_dir: ./datasets/imagenet_subset
  num_classes: 10
  class_names: ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
  train_split: 0.8
  val_split: 0.2
  test_split: 0.0

dataloader:
  batch_size: 32
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 2

model:
  backbone: timm_efficientnet_b0
  pretrained: true
  freeze_backbone: false
  dropout: 0.2

loss:
  name: focal
  alpha: 1.0
  gamma: 2.0

optimizer:
  name: adamw
  lr: 1e-3
  weight_decay: 1e-4
  betas: [0.9, 0.999]
  eps: 1e-8

scheduler:
  name: cosine_warmup
  warmup_epochs: 10
  total_epochs: 200
  min_lr: 1e-6

training:
  epochs: 200
  amp: true
  gradient_clip_norm: 1.0
  gradient_accumulation_steps: 1

metrics:
  task: multiclass
  num_classes: 10
  average: macro

callbacks:
  checkpoint:
    monitor: val_f1
    mode: max
    save_top_k: 5
    enabled: true
  
  early_stopping:
    monitor: val_f1
    mode: max
    patience: 20
    enabled: true
  
  sample_visualizer:
    num_samples: 20
    save_every_n_epochs: 5
    enabled: true
  
  confusion_matrix:
    save_every_n_epochs: 10
    enabled: true
  
  learning_rate:
    save_every_n_epochs: 10
    enabled: true

transforms:
  resize: 224
  horizontal_flip: true
  vertical_flip: false
  rotation: 15
  color_jitter: true
  hue_saturation_value: true
  gaussian_noise: true
  cutout: true
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  use_albumentations: true
