# U-Net Segmentation Configuration
# Example configuration for image segmentation with U-Net

experiment:
  name: unet_segmentation
  seed: 42

data:
  dataset_type: segmentation
  data_dir: ./datasets/segmentation/images
  mask_dir: ./datasets/segmentation/masks
  num_classes: 21
  class_names: ['background', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic_light', 'fire_hydrant', 'stop_sign', 'parking_meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow']
  mask_format: indexed
  train_split: 0.8
  val_split: 0.2
  test_split: 0.0

dataloader:
  batch_size: 16
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 2

model:
  backbone: timm_resnet50
  pretrained: true
  freeze_backbone: false

loss:
  name: combined
  ce_weight: 1.0
  dice_weight: 1.0
  focal_weight: 0.5
  lovasz_weight: 0.0

optimizer:
  name: adamw
  lr: 1e-4
  weight_decay: 1e-4
  betas: [0.9, 0.999]
  eps: 1e-8

scheduler:
  name: cosine_warmup
  warmup_epochs: 5
  total_epochs: 100
  min_lr: 1e-6

training:
  epochs: 100
  amp: true
  gradient_clip_norm: 1.0
  gradient_accumulation_steps: 1

metrics:
  task: segmentation
  num_classes: 21
  ignore_index: 255

callbacks:
  checkpoint:
    monitor: val_mean_iou
    mode: max
    save_top_k: 3
    enabled: true
  
  early_stopping:
    monitor: val_mean_iou
    mode: max
    patience: 15
    enabled: true
  
  sample_visualizer:
    num_samples: 8
    save_every_n_epochs: 5
    enabled: true
  
  confusion_matrix:
    save_every_n_epochs: 10
    enabled: true
  
  learning_rate:
    save_every_n_epochs: 10
    enabled: true

transforms:
  resize: 512
  horizontal_flip: true
  vertical_flip: false
  rotation: 15
  shift_scale_rotate: true
  elastic_transform: true
  grid_distortion: true
  color_jitter: true
  gaussian_noise: true
  gaussian_blur: true
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  use_albumentations: true
