# EfficientNet-B0 Classification Configuration
# Example configuration for image classification with EfficientNet-B0

input: /media/andra/Extreme Pro/CerviAssistAI/sipakmed_grouped_per_subject/test

experiment:
  name: efficientnet_classification_testing
  seed: 42

data:
  dataset_type: classification
  annotations_file: /media/andra/Extreme Pro/CerviAssistAI/sipakmed_grouped_per_subject/metadata.csv
  num_classes: 2
  test_data_dir: /media/andra/Extreme Pro/CerviAssistAI/sipakmed_grouped_per_subject/test
#  class_names: ['normal', 'suspecte']

dataloader:
  batch_size: 64
  num_workers: 0
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 2

model:
  backbone: timm_efficientnet_b0
  freeze_backbone: true
  pretrained: true
  dropout: 0.3

metrics:
  task: binary
  num_classes: 2
  average: macro

callbacks:

#  checkpoint:
#    monitor: f1
#    mode: max
#    save_top_k: 5
#    enabled: false

  sample_visualizer:
    num_samples: 20
    save_every_n_epochs: 5
    enabled: true

  confusion_matrix:
    save_every_n_epochs: 5
    enabled: true

transforms:
  resize: 224
  grayscale: true
  horizontal_flip: false
  vertical_flip: false
  rotation: 0
  color_jitter: false
  hue_saturation_value: false
  gaussian_noise: false
  cutout: false
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  use_albumentations: true
